# This is a basic workflow that is manually triggered

name: Format Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  format_check:
    runs-on: ubuntu-latest
    name: Format Check

    steps:
      - uses: actions/checkout@v4
      - run: wget -O ./Cubyz-fmt https://github.com/PixelGuys/Cubyz-formatter/releases/download/0.16.0-dev.1424+3/Cubyz-fmt-x86_64-linux
      - run: chmod +x ./Cubyz-fmt
      - run: |
          if ./Cubyz-fmt *.zig | grep -q . ; then
            git diff --color=always;
            exit 1;
          fi
      - run: |
          if ./Cubyz-fmt --zon *.zon | grep -q . ; then
            git diff --color=always;
            exit 1;
          fi
